DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL
);

CREATE TABLE transactions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       BIGINT         NOT NULL,
    amount            DECIMAL(10, 2) NOT NULL,
    transaction_date  DATE           NOT NULL,
    status            VARCHAR(20)    NOT NULL,
    type              VARCHAR(20)    NOT NULL,
    CONSTRAINT fk_transaction_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);
